### ISSUE TITLE
Oauth support

### ISSUE THREAD

**Issue by Meeshalk** [JeffreyHyer/alpaca-trade-api-php#1]
Can we have oauth support?

**Comment by JeffreyHyer** [comment]
Hey @Meeshalk, thanks for the request! It looks like Alpaca only supports key-based authentication currently. If that changes and they add support for OAuth I'll gladly add support for it in this library :+1:

**Comment by JeffreyHyer** [comment]
@Meeshalk I stand corrected! I've found the documentation for OAuth integrations. I'll look into adding support for it in this library.

**Comment by Meeshalk** [comment]
@JeffreyHyer Thanks for the response. I would like to help you in this repository. Let me know if we can discuss the integration.

**Comment by JeffreyHyer** [comment]
@Meeshalk I appreciate that, thank you. I've update the library to support OAuth authentication. You'll need to be using `v2.1.0`. You can see the docs in the README (under **OAuth**) for how to implement the flow to get an access token for an external user and make API calls on their behalf using the library.

Thanks for your patience!

**Comment by Meeshalk** [comment]
@JeffreyHyer Wow that was very quick, thanks a lot.
